arrays:
  - microphone_type: octahedron
    microphone_center: [0, 0, 3]
    rotation_angles_xyz: [0, 0, 0]
    mic_white_noise(dB): -60
  - microphone_type: octahedron
    microphone_center: [0, 20, 3]
    rotation_angles_xyz: [0, 0, 0]
    mic_white_noise(dB): -60
