# hyper parameter settings
speed_of_sound: 343  # Speed of sound in air (m/s)
sampling_rate: 48000  # microphone sampling rate

# total state number in one flight
state_num: 4 

# hyper parameters about drone
drone_types:
  - 'M2'
  - 'I2'
  - 'F-4'
  - 'S-9'

drone_states:
  - 'forward'
  - 'hover'
  - 'climb'
  - 'sink'

drone_states_weights:
  - 0.6  # probability of 'forward' 
  - 0.2  # probability of 'hover'
  - 0.1  # probability of 'climb'
  - 0.1  # probability of 'sink'

# each duration in one state (second)
state_dur_updown_min: 2
state_dur_updown_max: 5
state_dur_hover_min: 2 
state_dur_hover_max: 40
state_dur_forward_min: 2      
state_dur_forward_max: 20

climb_speed_max: 4  # the max climb speed of the drone
sink_speed_max: 3  # the max sink speed of the drone
speed_min: 2 # the minimum forward/climb/sink speed of the drone

modulation_range: 10  # micro modulation to adjust frequency of rotor during drone flight. from -modulation_range/2 to modulation_range/2
seg_dura_min: 0.02  # min segment duration of each micro modulation
seg_dura_max: 0.05  # max segment duration of each micro modulation
# the transition time when the drone changes its state (s)
change_time_min: 0.2  
change_time_max: 1  
# the transition shape coefficient
s_shape_coef_min: 5 
s_shape_coef_max: 10

# save data with n digits after the decimal point.
# Represents the number of decimal places
decimal_places: 2

# paramters about the pulse signal type
loudness: 3.0 # Loudness of the drone noise
signaltypes: # Choose the signal type of drone randomly, 'rect' or 'alternate'
  - rect
  - alternate
# The pulse length of the pulse signal
pulse_len_min: 2 
pulse_len_max: 5
# White noise level in the drone signal 
drone_white_noise_min: 0.005
drone_white_noise_max: 0.02


# the flying area of the drone (m)
x_min: -200
x_max: 200
y_min: -200
y_max: 200
z_min: 3
z_max: 50
# the range for the initial position of the drone
x_init: 0
y_init: 0 
z_init: 4
x_init_std: 10
y_init_std: 10
z_init_std: 1
# forword direction range
azimuth_min: 0
azimuth_max: 360

# wind speed range (m/s)
wind_speed_min: 1
wind_speed_max: 9

# Parameter settings for 3D environment space 
ground_ref_coeffs:
  - 0.65 # cement floor is between 0.55 and 0.75
  - 0.25 # grass is between 0.2 and 0.35 
wall_coeff: [0, 1, 0, -25]
wall_ref_coeff: 0.04 # between 0.03 and 0.05
# SNR (dB) refers to the ratio of the amplitude of drone signal to the amplitude of background noise
SNR: [200] 

# DOA parameters
resolution: 0.01 # Resolution value for saving real UAV DOA (default: 10ms)
# real time localizaton: frame parameters
frame_length: 0.032 # Frame length for real-time localization (seconds)
frame_hop: 0.032 # Frame hop for real-time localization (seconds)